### PR TITLE
LibSerialPort Backend

### PR DESCRIPTION
**Pull request by sjkelly**
Right now this is just LibSerialPort.jl rebased on top of SerialPorts.jl. 
TODO:
- [ ] Enable switch between python and libserialport backend
  - [ ] Enable libserialport as default on Linux
- [ ] relicense LibSerialPort.jl and SerialPorts.jl as LGPL3

### CODE REVIEW

**Comment by sjkelly** [comment]
cc @andrewadare

**Comment by andrewadare** [comment]
@sjkelly thanks, this is a good start. As suggested in https://github.com/JuliaIO/SerialPorts.jl/issues/14#issuecomment-272724981, I changed the  LibSerialPort.jl license to LGPLv3.

**Comment by scls19fr** [comment]
Any news?

**Comment by andrewadare** [comment]
I was thinking about revisiting this project once a Julia 0.7/1.0 RC comes out, which has seemed like it was right on the verge of happening for many months.

**Comment by scls19fr** [comment]
Julia 1.0.0 is now out since 8/8/2018
see https://julialang.org/downloads/

**Comment by scls19fr** [comment]
https://julialang.org/blog/2018/08/one-point-zero

**Comment by sjkelly** [comment]
Closing this as LibSerialPort is now in JuliaIO.

**Pull request closed without merging**
